version: "3.7"

services:
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=zampapp
      - MYSQL_USER=zampapp
      - MYSQL_PASSWORD=zampapp
      - MYSQL_ROOT_PASSWORD=darootpass
      - TZ=Europe/Rome
    ports:
      - "3306:3306"
    command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
  go:
    image: "brumbrum/golang-develop:develop-brumbrum"
    volumes:
      - .:/data:z
    links:
      - db
    ports:
      - 8000:80
    command: "gow run ."
